<?php
namespace Artax\Http;

class ClientHelper extends Client {
    public function getContextOptions() {
        return $this->contextOptions;
    }
}

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-19 at 11:42:18.
 */
class ClientTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var ClientHelper
     */
    protected $client;

    protected function setUp() {
        $this->client = new ClientHelper;
    }

    /**
     * @covers Artax\Http\Client::setMaxRedirects
     */
    public function testSetMaxRedirects() {
        $this->client->setMaxRedirects(0);

        $options = $this->client->getContextOptions();

        $this->assertArrayHasKey('http', $options);
        $this->assertArrayHasKey('max_redirects', $options['http']);

        $this->assertEquals(0, $options['http']['max_redirects']);


        $this->client->setMaxRedirects(20);

        $options = $this->client->getContextOptions();

        $this->assertArrayHasKey('http', $options);
        $this->assertArrayHasKey('max_redirects', $options['http']);

        $this->assertEquals(20, $options['http']['max_redirects']);
    }

    /**
     * @covers Artax\Http\Client::send
     */
    public function testSend() {
    }
}
