<?php

/**
 * Artax MatcherInterface Interface File
 * 
 * PHP version 5.4
 * 
 * @category   artax
 * @package    core
 * @author     Daniel Lowrey <rdlowrey@gmail.com>
 */

namespace artax {
  
  /**
   * MatcherInterface Interface
   * 
   * @category   artax
   * @package    core
   * @author     Daniel Lowrey <rdlowrey@gmail.com>
   */
  interface MatcherInterface
  {
    /**
     * Does the request match a route from the supplied route list?
     * 
     * @param RequestInterface $request The request object to match
     * 
     * @return bool Returns `TRUE` on match or `FALSE` if no match
     */
    public function match(RequestInterface $request);
    
    /**
     * Retrieve the matched route's dot-notation controller string
     * 
     * @return string
     */
    public function getController();
    
    /**
     * Retrieve route arguments generated by a match from the RouteList
     * 
     * @return array
     */
    public function getArgs();
  }
}
