<?php

/**
 * MatcherInterface File
 * 
 * PHP version 5.4
 * 
 * @category   Artax
 * @package    core
 * @subpackage routing
 * @author     Daniel Lowrey <rdlowrey@gmail.com>
 */

namespace Artax\Routing {
  
  /**
   * MatcherInterface
   * 
   * @category   Artax
   * @package    core
   * @subpackage routing
   * @author     Daniel Lowrey <rdlowrey@gmail.com>
   */
  interface MatcherInterface
  {
    /**
     * Does the request match a route from the route list?
     */
    public function match();
    
    /**
     * Retrieve the matched route's dot-notation controller string
     */
    public function getController();
    
    /**
     * Retrieve route arguments generated by a match from the RouteList
     */
    public function getArgs();
  }
}
