<?php

/**
 * MatcherInterface File
 * 
 * PHP version 5.4
 * 
 * @category   artax
 * @package    core
 * @subpackage routing
 * @author     Daniel Lowrey <rdlowrey@gmail.com>
 */

namespace artax\routing {
  
  /**
   * MatcherInterface
   * 
   * @category   artax
   * @package    core
   * @subpackage routing
   * @author     Daniel Lowrey <rdlowrey@gmail.com>
   */
  interface MatcherInterface
  {
    /**
     * Does the request match a route from the supplied route list?
     * 
     * @param RequestInterface $request   The request object to match
     * @param RouteList        $routeList The list of routes to match against
     */
    public function match(RequestInterface $request, RouteList $routeList);
    
    /**
     * Retrieve the matched route's dot-notation controller string
     */
    public function getController();
    
    /**
     * Retrieve route arguments generated by a match from the RouteList
     */
    public function getArgs();
  }
}
