<?php

/**
 * HttpExControllerInterface File
 * 
 * PHP version 5.4
 * 
 * @category   artax
 * @package    blocks
 * @subpackage http
 * @author     Daniel Lowrey <rdlowrey@gmail.com>
 */

namespace artax\blocks\http {

  /**
   * HttpExControllerInterface
   * 
   * Requires that an HTTP controller is provided to access the response object
   * generated by HttpController objects.
   * 
   * @category   artax
   * @package    blocks
   * @subpackage http
   * @author     Daniel Lowrey <rdlowrey@gmail.com>
   */
  interface HttpExControllerInterface extends \artax\ExControllerInterface
  {
    /**
     * Getter method for $response object property
     */
    public function getResponse();
  }
}
