<?php

/**
 * HttpControllerInterface File
 * 
 * PHP version 5.4
 * 
 * @category   artax
 * @package    blocks
 * @subpackage http
 * @author     Daniel Lowrey <rdlowrey@gmail.com>
 */

namespace artax\blocks\http {

  /**
   * HttpControllerInterface
   * 
   * Requires that an interface is provided to access the response object
   * generated by HttpController objects.
   * 
   * @category   artax
   * @package    blocks
   * @subpackage http
   * @author     Daniel Lowrey <rdlowrey@gmail.com>
   */
  interface HttpControllerInterface
  {
    /**
     * A magic invocation method to execute the controller's work method(s)
     */
    public function __invoke();
    
    /**
     * Getter method for $response object property
     */
    public function getResponse();
  }
}
